var lang_es = [
    {
        "institucion": "Casa Real España",
        "icono": "real",
        "pais": "españa",
        "region": "madrid",
        "persona": "",
        "cargo": "",
        "twitter": "https://twitter.com/casareal?lang=es",
        "instagram": "x",
        "facebook": "https://www.facebook.com/FelipeReyfelip",
        "linkedin": "x"
    },
    {
        "institucion": "República de Portugal",
        "icono": "institucion",
        "pais": "portugal",
        "region": "lisboa",
        "persona": "Marcelo Rebelo de Sousa",
        "cargo": "Presidente de la República de Portugal",
        "twitter": "https://twitter.com/govpt?lang=es",
        "instagram": "x",
        "facebook": "x",
        "linkedin": "https://www.linkedin.com/company/rep%C3%BAblica-portuguesa---xxi-governo/"
    },
    {
        "institucion": "Gobierno de España",
        "icono": "institucion",
        "pais": "españa",
        "region": "madrid",
        "persona": "Íñigo Méndez de Vigo",
        "cargo": "Ministro de Educación, Cultura y Deporte",
        "twitter": "https://twitter.com/desdelamoncloa?lang=es",
        "instagram": "x",
        "facebook": "x",
        "linkedin": "x"
    },
    {
        "institucion": "Banco Santander",
        "icono": "banco",
        "pais": "españa",
        "region": "madrid",
        "persona": "Ana Botín",
        "cargo": "Presidenta de Universia y Banco Santander",
        "twitter": "https://twitter.com/bancosantander?lang=es",
        "facebook": "https://www.facebook.com/bancosantander/",
        "linkedin": "https://www.linkedin.com/company/banco-santander/?originalSubdomain=es"
    },
    {
        "institucion": "Junta de Castilla y León ",
        "icono": "institucion",
        "pais": "españa",
        "region": "salamanca",
        "persona": "Juan Vicente Herrera Campo",
        "cargo": "Presidente de la Junta de Castilla y León",
        "twitter": "https://twitter.com/jcyl",
        "instagram": "x",
        "facebook": "https://www.facebook.com/juntadecastillayleon/",
        "linkedin": "https://www.linkedin.com/company/42598/"
    },
    {
        "institucion": "Ayuntamiento de Salamanca",
        "icono": "institucion",
        "pais": "españa",
        "region": "salamanca",
        "persona": "Alfonso Fernández Mañueco",
        "cargo": "Alcalde de Salamanca",
        "twitter": "https://twitter.com/aytoSalamanca",
        "instagram": "x",
        "facebook": "https://www.facebook.com/aytosalamanca",
        "linkedin": "https://www.linkedin.com/company/ayuntamiento-de-salamanca/"
    },
    {
        "institucion": "Universidad de Buenos Aires",
        "icono": "institucion",
        "pais": "argentina",
        "region": "buenos aires",
        "persona": "Alberto Barbieri",
        "cargo": "Presidente Comité Internacional",
        "twitter": "https://twitter.com/UBAonline",
        "instagram": "https://www.instagram.com/ubaoficial/",
        "facebook": "https://www.facebook.com/ubaonline/",
        "linkedin": "https://www.linkedin.com/school/338240/"
    },
    {
        "institucion": "Universidad de Salamanca",
        "icono": "universidad",
        "pais": "españa",
        "region": "salamanca",
        "persona": "Ricardo Rivero",
        "cargo": "Rector de la Universidad de Salamanca",
        "twitter": "https://twitter.com/usal",
        "instagram": "https://www.instagram.com/usal/",
        "facebook": "https://www.facebook.com/universidaddesalamanca/",
        "linkedin": "https://www.linkedin.com/school/57126/"
    },
    {
        "institucion": "Universidad de Gothemburg",
        "icono": "universidad",
        "pais": "alemania",
        "region": "gothemburg",
        "persona": "Pan Fredman",
        "cargo": "Presidenta de la Asociación Internacional de Universidades - Videpresidenta de la Universidad de Gothemburg",
        "twitter": "https://twitter.com/goteborgsuni",
        "instagram": "https://www.instagram.com/universityofgothenburg/",
        "facebook": "https://www.facebook.com/universityofgothenburg/",
        "linkedin": "https://www.linkedin.com/school/432169/"
    },
    {
        "institucion": "Universidad de Santiago de Compostela",
        "icono": "universidad",
        "pais": "españa",
        "region": "santiago de compostela",
        "persona": "María José Alonso",
        "cargo": "Catedrática en Farmacología por la Universidad de Santiago de Compostela",
        "twitter": "https://twitter.com/universidadeusc",
        "instagram": "x",
        "facebook": "https://www.facebook.com/UniversidadeUSC/",
        "linkedin": "https://www.linkedin.com/school/universidad-de-santiago-de-compostela/"
    },
    {
        "institucion": "Samasource",
        "icono": "institucion",
        "pais": "usa",
        "region": "san francisco",
        "persona": "Leila Janah",
        "cargo": "Fundadora y CEO of Samasource",
        "twitter": "https://twitter.com/Samasource",
        "instagram": "https://www.instagram.com/samasource/",
        "facebook": "https://www.facebook.com/samaimpact/",
        "linkedin": "https://www.linkedin.com/company/410136/"
    },
    {
        "institucion": "Instituto Tecnológico y de Estudios Superiores de Monterrey ",
        "icono": "universidad",
        "pais": "méxico",
        "region": "monterrey",
        "persona": "David Garza",
        "cargo": "Rector del Instituto Tecnológico y de Estudios Superiores de Monterrey ",
        "twitter": "https://twitter.com/tecdemty",
        "instagram": "https://www.instagram.com/tecdemty/",
        "facebook": "https://www.facebook.com/tecdemty/",
        "linkedin": "x"
    },
    {
        "institucion": "Santander Universidades y Universia Holding",
        "icono": "banco",
        "pais": "españa",
        "region": "madrid",
        "persona": "Javier Roglá",
        "cargo": "Director Global Santander Universidades y CEO de Universia Holding",
        "twitter": "https://twitter.com/universia",
        "instagram": "https://www.instagram.com/universia_net/",
        "facebook": "https://www.facebook.com/universianet/",
        "linkedin": "https://www.linkedin.com/company/universia-corporativo/"
    },
    {
        "institucion": "Santander Universidades México / Universia México",
        "icono": "banco",
        "pais": "méxico",
        "region": "ciudad de méxico",
        "persona": "Arturo Cherbowski ",
        "cargo": "Director general Santander Universidades México / Universia México",
        "twitter": "https://twitter.com/UniversiaMex             https://twitter.com/santanderunimx",
        "instagram": "https://www.instagram.com/universia_mx/           http://instagram.com/santanderunimx",
        "facebook": "https://www.facebook.com/universia.mexico/          http://www.facebook.com/santanderunimx",
        "linkedin": "https://www.linkedin.com/company/28158455/"
    },
    {
        "institucion": "Universidad de Sao Paulo ",
        "icono": "universidad",
        "pais": "brasil",
        "region": "sao paulo",
        "persona": "Marco Antonio Zago",
        "cargo": "Rector de la Universidad de Sao Paulo ",
        "twitter": "https://twitter.com/usponline",
        "instagram": "x",
        "facebook": "https://www.facebook.com/usponline/",
        "linkedin": "https://www.linkedin.com/school/universidade-de-s-o-paulo/"
    },
    {
        "institucion": "Santander Universidades Corporativo",
        "icono": "banco",
        "pais": "españa",
        "region": "madrid",
        "persona": "José Manuel de la Chica ",
        "cargo": "CTO Santander Universidades corporativo",
        "twitter": "https://twitter.com/universia",
        "instagram": "https://www.instagram.com/universia_net",
        "facebook": "https://www.facebook.com/universianet/",
        "linkedin": "https://www.linkedin.com/company/28162346/"
    },
    {
        "institucion": "Universidad de Oporto",
        "icono": "universidad",
        "pais": "portugal",
        "region": "oporto",
        "persona": "Sebastião Feyo de Azevedo",
        "cargo": "Rector de la Universidad de Oporto",
        "twitter": "https://twitter.com/UPorto",
        "instagram": "https://www.instagram.com/uporto/",
        "facebook": "https://www.facebook.com/universidadedoporto/",
        "linkedin": "https://www.linkedin.com/school/universidadedoporto/"
    },
    {
        "institucion": "Universidad de Cantabria ",
        "icono": "universidad",
        "pais": "españa",
        "region": "cantabria",
        "persona": "Ángel Pazos Carro",
        "cargo": "Rector de la Universidad de Cantabria ",
        "twitter": "https://twitter.com/unican",
        "instagram": "https://www.instagram.com/universidaddecantabria/",
        "facebook": "https://www.facebook.com/universidaddecantabria",
        "linkedin": "https://www.linkedin.com/school/38246/"
    },
    {
        "institucion": "CINVESTAV-IPN ",
        "icono": "institucion",
        "pais": "méxico",
        "region": "ciudad de méxico",
        "persona": "Inés Dussel",
        "cargo": "Profesora investigadora del Departamento de Investigaciones Educativas",
        "twitter": "https://twitter.com/cinvestav",
        "instagram": "https://www.instagram.com/cinvestav/",
        "facebook": "https://www.facebook.com/CINVESTAV/",
        "linkedin": "https://www.linkedin.com/company/79748/"
    },
    {
        "institucion": "Universidad de Buenos Aires",
        "icono": "universidad",
        "pais": "argentina",
        "region": "buenos aires",
        "persona": "María Catalina Nosiglia",
        "cargo": "Secretaria de Asuntos Académicos de la Universidad de Buenos Aires",
        "twitter": "https://twitter.com/ubaonline?lang=es",
        "instagram": "https://www.instagram.com/ubaoficial/",
        "facebook": "https://www.facebook.com/ubaonline",
        "linkedin": "https://www.linkedin.com/school/338240/"
    },
    {
        "institucion": "Instituto Tecnológico de Buenos Aires",
        "icono": "universidad",
        "pais": "argentina",
        "region": "buenos aires",
        "persona": "José Luis Roces",
        "cargo": "Rector del Instituto Tecnológico de Buenos Aires",
        "twitter": "https://twitter.com/itba?lang=es",
        "instagram": "https://www.instagram.com/itbauniversidad/",
        "facebook": "X",
        "linkedin": "https://www.linkedin.com/school/15090642/"
    },
    {
        "institucion": "Universidad Politécnica Madrid",
        "icono": "universidad",
        "pais": "españa",
        "region": "madrid",
        "persona": "Javier Uceda",
        "cargo": "Director de la Cátedra UNESCO de gestión y política universitaria",
        "twitter": "https://twitter.com/La_UPM/",
        "instagram": "https://www.instagram.com/somosupm/",
        "facebook": "https://www.facebook.com/universidadpolitecnicademadrid",
        "linkedin": "https://www.linkedin.com/school/166617/"
    },
    {
        "institucion": "Facultad Latinoamericana de Ciencias Sociales",
        "icono": "universidad",
        "pais": "argentina",
        "region": "buenos aires",
        "persona": "Luis Alberto Quevedo",
        "cargo": "Investigador de la Facultad Latinoamericana de Ciencias Sociales.",
        "twitter": "https://twitter.com/FLACSOSG",
        "instagram": "x",
        "facebook": "https://www.facebook.com/flacso.general",
        "linkedin": "https://www.linkedin.com/in/flacso-secretar%C3%ADa-general-b3348156/"
    },
    {
        "institucion": "Universidad de Coimbra",
        "icono": "universidad",
        "pais": "portugal",
        "region": "coimbra",
        "persona": "João Gabriel Silva",
        "cargo": "Rector Universidad de Coimbra",
        "twitter": "https://twitter.com/univdecoimbra",
        "instagram": "https://www.instagram.com/ucoimbra/",
        "facebook": "https://www.facebook.com/univdecoimbra",
        "linkedin": "https://www.linkedin.com/school/universidade-de-coimbra/"
    },
    {
        "institucion": "Santander Universidades Portugal ",
        "icono": "banco",
        "pais": "portugal",
        "region": "lisboa",
        "persona": "Marcos Soares Ribeiro",
        "cargo": "Director Santander Universidades ",
        "twitter": "https://twitter.com/santanderuni_PT",
        "instagram": "https://www.instagram.com/santanderuni_PT/",
        "facebook": "https://www.facebook.com/santanderuniversidadesportugal/",
        "linkedin": "x"
    },
    {
        "institucion": "Universidad Camilo José Cela",
        "icono": "institucion",
        "pais": "españa",
        "region": "madrid",
        "persona": "Samuel Martín-Barbero ",
        "cargo": "Rector UCJC",
        "twitter": "https://twitter.com/universidadcjc",
        "instagram": "https://www.instagram.com/universidadcjc/",
        "facebook": "https://www.facebook.com/universidadcjc?ref=nf",
        "linkedin": "https://www.linkedin.com/school/15094078/"
    },
    {
        "institucion": "Universidad Autónoma de México",
        "icono": "universidad",
        "pais": "méxico",
        "region": "ciudad de méxico",
        "persona": "Dr. Enrique Graue Wiechers",
        "cargo": "Rector de la Universidad Autónoma de México",
        "twitter": "https://twitter.com/unam_mx",
        "instagram": "https://www.instagram.com/unam_mx/",
        "facebook": "https://www.facebook.com/UNAM.MX.Oficial",
        "linkedin": "https://www.linkedin.com/school/15248522/"
    },
    {
        "institucion": "Universidad de Talca",
        "icono": "universidad",
        "pais": "chile",
        "region": "talca",
        "persona": "Dr. Álvaro Rojas Marín",
        "cargo": "Rector de la Universidad de Talca",
        "twitter": "https://twitter.com/utalca",
        "instagram": "https://www.instagram.com/utalca/",
        "facebook": "https://www.facebook.com/utalca",
        "linkedin": "https://www.linkedin.com/in/utalca/"
    },
    {
        "institucion": "Universidad de Friburgo",
        "icono": "universidad",
        "pais": "alemania",
        "region": "friburgo",
        "persona": "Hans-Jochen Schiewer",
        "cargo": "Rector de la Universidad de Friburgo ",
        "twitter": "https://twitter.com/UniFreiburg",
        "instagram": "https://www.instagram.com/unifreiburg/",
        "facebook": "https://www.facebook.com/unifreiburg",
        "linkedin": "https://www.linkedin.com/school/albert-ludwigs-universit-t-freiburg-im-breisgau/"
    },
    {
        "institucion": "edX",
        "icono": "institucion",
        "pais": "estados unidos",
        "region": "massachusetts",
        "persona": "Anant Agarwal",
        "cargo": "CEO de edX ",
        "twitter": "https://twitter.com/edXOnline?lang=es",
        "instagram": "https://www.instagram.com/edxonline/",
        "facebook": "https://www.facebook.com/edxespanol/?brand_redir=143664199098284",
        "linkedin": "https://www.linkedin.com/school/2746406/"
    },
    {
        "institucion": "Coursera",
        "icono": "institucion",
        "pais": "estados unidos",
        "region": "california",
        "persona": "Jeff Maggioncalda",
        "cargo": "CEO de Coursera ",
        "twitter": "https://twitter.com/coursera",
        "instagram": "https://www.instagram.com/coursera/",
        "facebook": "https://www.facebook.com/Coursera/",
        "linkedin": "https://www.linkedin.com/company/2453129/"
    },
    {
        "institucion": "Universidad Nacional de Quilmes",
        "icono": "universidad",
        "pais": "argentina",
        "region": "quilmes",
        "persona": "Dr. Alejandro Villar",
        "cargo": "Rector de la Universidad Nacional de Quilmes",
        "twitter": "https://twitter.com/UNQoficial",
        "instagram": "https://www.instagram.com/unq_oficial/",
        "facebook": "https://www.facebook.com/UNQoficial/",
        "linkedin": "https://www.linkedin.com/school/61238/"
    },
    {
        "institucion": "Pontificia Universidad Católica ",
        "icono": "universidad",
        "pais": "chile",
        "region": "santiago de chile",
        "persona": "Rector Ignacio Sánchez Díaz",
        "cargo": "Pontificia Universidad Católica",
        "twitter": "https://twitter.com/ucatolica",
        "instagram": "https://www.instagram.com/ucatolicaoficial/",
        "facebook": "https://www.facebook.com/ucatolica",
        "linkedin": "https://www.linkedin.com/school/399270/"
    },
    {
        "institucion": "Universia Chile",
        "icono": "banco",
        "pais": "chile",
        "region": "santiago de chile",
        "persona": "José Pedro Fuenzalida",
        "cargo": "Director de Universia Chile",
        "twitter": "https://twitter.com/UniversiaChile",
        "instagram": "https://www.instagram.com/universiachile/",
        "facebook": "https://www.facebook.com/universia.chile/",
        "linkedin": "https://www.linkedin.com/company/28159146/"
    },
    {
        "institucion": "Universidad de Santiago de Chile",
        "icono": "universidad",
        "pais": "chile",
        "region": "santiago de chile",
        "persona": "Juan Zolezzi",
        "cargo": "Rector Universidad de Santiago de Chile",
        "twitter": "https://twitter.com/usach",
        "instagram": "https://www.instagram.com/udesantiagocl/",
        "facebook": "https://www.facebook.com/universidaddesantiago/",
        "linkedin": "https://www.linkedin.com/school/universidad-de-santiago-de-chile/"
    },
    {
        "institucion": "Universidad de Santiago de Compostela",
        "icono": "universidad",
        "pais": "españa",
        "region": "galicia",
        "persona": "Juan Viaño",
        "cargo": "Rector de la Universidad de Santiago de Compostela",
        "twitter": "https://twitter.com/universidadeusc",
        "instagram": "x",
        "facebook": "https://www.facebook.com/UniversidadeUSC/",
        "linkedin": "https://www.linkedin.com/school/universidad-de-santiago-de-compostela/"
    },
    {
        "institucion": "Universidad de los Andes",
        "icono": "universidad",
        "pais": "colombia",
        "region": "bogotá",
        "persona": "Pablo Navas",
        "cargo": "Rector de la Universidad de los Andes",
        "twitter": "https://twitter.com/Uniandes",
        "instagram": "https://www.instagram.com/uniandes/",
        "facebook": "https://www.facebook.com/Universidad-de-los-Andes-312867483159/",
        "linkedin": "https://www.linkedin.com/school/universidad-de-los-andes/"
    },
    {
        "institucion": "Universidad de Navarra",
        "icono": "universidad",
        "pais": "españa",
        "region": "navarra",
        "persona": "Concepción Naval",
        "cargo": "Decana Universidad de Navarra",
        "twitter": "https://twitter.com/unav",
        "instagram": "https://www.instagram.com/universidaddenavarra/",
        "facebook": "https://www.facebook.com/unav",
        "linkedin": "https://www.linkedin.com/school/26328/"
    },
    {
        "institucion": "Universidad Estadual Paulista",
        "icono": "universidad",
        "pais": "brasil",
        "region": "sao paulo",
        "persona": "Sandro Roberto Valentini",
        "cargo": "Rector de la Universidad Estadual Paulista",
        "twitter": "https://twitter.com/Unesp_Oficial",
        "instagram": "https://www.instagram.com/unesp_oficial/",
        "facebook": "https://www.facebook.com/UNESPUniversidadeEstadualPaulista/",
        "linkedin": "https://www.linkedin.com/company/21927/"
    },
    {
        "institucion": "Pontificia Universidad Javeriana ",
        "icono": "universidad",
        "pais": "colombia",
        "region": "bogotá",
        "persona": "Rector Padre Jorge H. Peláez Piedrahita SJ",
        "cargo": "Pontificia Universidad Javeriana",
        "twitter": "https://twitter.com/unijaveriana",
        "instagram": "https://www.instagram.com/unijaveriana/",
        "facebook": "https://www.facebook.com/unijaveriana",
        "linkedin": "https://www.linkedin.com/school/pontificia-universidad-javeriana/"
    },
    {
        "institucion": "Universia Colombia",
        "icono": "banco",
        "pais": "colombia",
        "region": "bogotá",
        "persona": "Ruth Polchlopek",
        "cargo": "Directora general de Universia Colombia",
        "twitter": "https://twitter.com/UniversiaCol",
        "instagram": "https://www.instagram.com/universia_co/",
        "facebook": "https://www.facebook.com/universia.colombia/",
        "linkedin": "https://www.linkedin.com/company/28164242/"
    },
    {
        "institucion": "Universidad de A Coruña",
        "icono": "universidad",
        "pais": "españa",
        "region": "galicia",
        "persona": "Julio E. Abalde Alonso",
        "cargo": "Rector de la Universidad de A Coruña",
        "twitter": "https://twitter.com/UDC_gal",
        "instagram": "https://www.instagram.com/udc_gal/",
        "facebook": "https://www.facebook.com/udc.gal",
        "linkedin": "https://www.linkedin.com/school/47842/"
    },
    {
        "institucion": "Universitat Oberta de Catalunya",
        "icono": "universidad",
        "pais": "españa",
        "region": "cataluña",
        "persona": "Josep Planell",
        "cargo": "Rector de la UOC",
        "twitter": "https://twitter.com/UOCuniversitat",
        "instagram": "https://www.instagram.com/uocuniversitat/",
        "facebook": "https://www.facebook.com/UOC.universitat",
        "linkedin": "https://www.linkedin.com/school/uoc/"
    },
    {
        "institucion": "Universidad de Monterrey",
        "icono": "universidad",
        "pais": "méxico",
        "region": "monterrey",
        "persona": "Dr. Antonio J. Dieck Assad",
        "cargo": "Rector de la Universidad de Monterrey ",
        "twitter": "https://twitter.com/udem",
        "instagram": "x",
        "facebook": "https://www.facebook.com/universidaddemonterrey",
        "linkedin": "https://www.linkedin.com/school/27891/"
    },
    {
        "institucion": "Universidad Federal de Sao Paulo",
        "icono": "universidad",
        "pais": "brasil",
        "region": "sao paulo",
        "persona": "Rectora Soraya Soubhi Smaili",
        "cargo": "Universidad Federal de Sao Paulo",
        "twitter": "https://twitter.com/federaldesp",
        "instagram": "x",
        "facebook": "https://www.facebook.com/UnifespOficial/",
        "linkedin": "https://www.linkedin.com/school/33457/"
    },
    {
        "institucion": "Universidad de León",
        "icono": "universidad",
        "pais": "españa",
        "region": "león",
        "persona": "Javier Vidal",
        "cargo": "Catedrático de la Universidad de León",
        "twitter": "https://twitter.com/unileon",
        "instagram": "https://www.instagram.com/unileon_es/",
        "facebook": "https://www.facebook.com/unileon",
        "linkedin": "https://www.linkedin.com/school/108566/"
    },
    {
        "institucion": "Universidad Complutense de Madrid",
        "icono": "universidad",
        "pais": "españa",
        "region": "madrid",
        "persona": "Carlos Andradas",
        "cargo": "Rector Universidad Complutense de Madrid",
        "twitter": "https://twitter.com/unicomplutense",
        "instagram": "https://www.instagram.com/uni.complutense/",
        "facebook": "https://www.facebook.com/UniComplutense",
        "linkedin": "https://www.linkedin.com/school/universidadcomplutense/"
    },
    {
        "institucion": "Santander Universidades España / Universia España",
        "icono": "banco",
        "pais": "españa",
        "region": "madrid",
        "persona": "Susana García Espinel ",
        "cargo": "Directora general Santander Universidades España / Universia España",
        "twitter": "https://twitter.com/Universia",
        "instagram": "https://www.instagram.com/universia_net",
        "facebook": "https://www.facebook.com/universianet/",
        "linkedin": "https://www.linkedin.com/company/28162346/"
    },
    {
        "institucion": "Universidad de Guadalajara",
        "icono": "universidad",
        "pais": "méxico",
        "region": "guadalajara",
        "persona": "Itzcóatl Tonatiuh Bravo Padilla",
        "cargo": "Rector Mtro. Universidad de Guadalajara",
        "twitter": "https://twitter.com/udg_oficial",
        "instagram": "https://www.instagram.com/udg_oficial/",
        "facebook": "https://www.facebook.com/udg.mx",
        "linkedin": "https://www.linkedin.com/school/957560/"
    },
    {
        "institucion": "Instituto Tecnológico de massachusetts, MIT",
        "icono": "institucion",
        "pais": "estados unidos",
        "region": "massachusetts",
        "persona": "Dr. Rafael Reif",
        "cargo": "Rector del Instituto Tecnológico de massachusetts",
        "twitter": "https://twitter.com/mit",
        "instagram": "https://www.instagram.com/mitpics/",
        "facebook": "https://www.facebook.com/MITnews",
        "linkedin": "https://www.linkedin.com/school/1503/"
    },
    {
        "institucion": "Universidad de Alcalá",
        "icono": "universidad",
        "pais": "españa",
        "region": "madrid",
        "persona": "Dr. Fernando Galván",
        "cargo": "Rector de la Universidad de Alcalá",
        "twitter": "https://twitter.com/uahes",
        "instagram": "https://www.instagram.com/uahes/",
        "facebook": "https://www.facebook.com/UniversidadDeAlcala",
        "linkedin": "https://www.linkedin.com/school/47844/"
    },
    {
        "institucion": "Lead to Change ",
        "icono": "institucion",
        "pais": "españa",
        "region": "madrid",
        "persona": "Xavier Marcet",
        "cargo": "CEO de Lead to Change",
        "twitter": "https://twitter.com/leadtochangeltc",
        "instagram": "X",
        "facebook": "X",
        "linkedin": "https://www.linkedin.com/company/lead-to-change/"
    },
    {
        "institucion": "Instituto Tecnológico de massachusetts, MIT",
        "icono": "institucion",
        "pais": "estados unidos",
        "region": "massachusetts",
        "persona": "Shigeru Miyagawa",
        "cargo": "Senior Associate Dean for Open Learning",
        "twitter": "https://twitter.com/mit",
        "instagram": "https://www.instagram.com/mitpics/",
        "facebook": "https://www.facebook.com/MITnews",
        "linkedin": "https://www.linkedin.com/school/1503/"
    },
    {
        "institucion": "Universidad Autónoma de Barcelona",
        "icono": "universidad",
        "pais": "españa",
        "region": "barcelona",
        "persona": "Margarita Arboix",
        "cargo": "Rectora de la Universidad Autónoma de Barcelona",
        "twitter": "https://twitter.com/UABBarcelona",
        "instagram": "https://www.instagram.com/uabbarcelona/",
        "facebook": "https://www.facebook.com/uabbarcelona",
        "linkedin": "https://www.linkedin.com/school/234979/"
    },
    {
        "institucion": "Banco Interamericano de Desarrollo ",
        "icono": "institucion",
        "pais": "estados unidos",
        "region": "washington dc",
        "persona": "Juan Carlos Navarro",
        "cargo": "Líder Técnico Principal de Ciencia y Tecnología. División de competitividad e Innovación",
        "twitter": "https://twitter.com/el_bid?lang=es",
        "instagram": "https://www.instagram.com/el_bid/?hl=es",
        "facebook": "https://www.facebook.com/BancoInteramericano/?ref=br_rs",
        "linkedin": "https://www.linkedin.com/company/164401/"
    },
    {
        "institucion": "Siemens España",
        "icono": "institucion",
        "pais": "españa",
        "region": "madrid",
        "persona": "Rosa García García",
        "cargo": "Vicepresidenta del Consejo Social de la Universidad Carlos III de Madrid y Presidenta y Consejera Delegada de Siemens España",
        "twitter": "https://twitter.com/siemens_es",
        "instagram": "https://www.instagram.com/siemens_es/",
        "facebook": "https://www.facebook.com/SiemensSpain/",
        "linkedin": "https://www.linkedin.com/company/siemens/"
    },
    {
        "institucion": "Genetrix S.L. ",
        "icono": "institucion",
        "pais": "españa",
        "region": "madrid",
        "persona": "Cristina Garmendia",
        "cargo": "Exministra de Ciencia e Innovación. Presidenta de Genetrix S.L. ",
        "twitter": "x",
        "instagram": "x",
        "facebook": "x",
        "linkedin": "https://www.linkedin.com/company/102587/"
    },
    {
        "institucion": "Pontificia Universidad Católica de Río de Janeiro",
        "icono": "universidad",
        "pais": "brasil",
        "region": "rio de janeiro",
        "persona": "Rector Pd. Josafá",
        "cargo": "Rector PUC Rio de Janeiro ",
        "twitter": "x",
        "instagram": "x",
        "facebook": "https://www.facebook.com/pucrj/",
        "linkedin": "https://www.linkedin.com/school/165595/"
    },
    {
        "institucion": "Universia Brasil ",
        "icono": "banco",
        "pais": "brasil",
        "region": "sao paulo",
        "persona": "Anderson Pereira",
        "cargo": "Director general de Universia Brasil",
        "twitter": "https://twitter.com/universiabrasil",
        "instagram": "https://www.instagram.com/universiabrasil_oficial/",
        "facebook": "https://www.facebook.com/brasil.universia/",
        "linkedin": "https://www.linkedin.com/company/3302408/"
    },
    {
        "institucion": "Universidad Jaume I ",
        "icono": "universidad",
        "pais": "españa",
        "region": "castellón de laplana",
        "persona": "Vicent Climent Jordà",
        "cargo": "Rector de la Universidad Jaume I ",
        "twitter": "https://twitter.com/uji_noticies",
        "instagram": "https://www.instagram.com/ujiuniversitat/",
        "facebook": "https://www.facebook.com/universitatjaumei",
        "linkedin": "https://www.linkedin.com/school/universitat-jaume-i/"
    },
    {
        "institucion": "Universidade Federal do Rio Grande do Sul ",
        "icono": "universidad",
        "pais": "brasil",
        "region": "rio grande do sul",
        "persona": "Dr. Rui Vicente Oppermann",
        "cargo": "Reitor da Universidade Federal do Rio Grande do Sul",
        "twitter": "https://twitter.com/ufrgsnoticias",
        "instagram": "https://www.instagram.com/ufrgsnoticias/?hl=pt",
        "facebook": "https://www.facebook.com/ufrgsnoticias/",
        "linkedin": "https://www.linkedin.com/school/10866/"
    },
    {
        "institucion": "UNED",
        "icono": "universidad",
        "pais": "españa",
        "region": "madrid",
        "persona": "Esther Souto Galván",
        "cargo": "Vicerrectora de Investigación e Internacionalización. Universidad Nacional de Educación a Distancia",
        "twitter": "https://twitter.com/uned",
        "instagram": "X",
        "facebook": "https://www.facebook.com/UNED.ES",
        "linkedin": "https://www.linkedin.com/company/uned/"
    },
    {
        "institucion": "Universidad Católica Portuguesa",
        "icono": "universidad",
        "pais": "portugal",
        "region": "lisboa",
        "persona": "Isabel Maria Oliveira Capeloa Gil",
        "cargo": "Rectora de la Universidad Católica Portuguesa",
        "twitter": "X",
        "instagram": "https://www.instagram.com/universidadecatolicaportuguesa/",
        "facebook": "https://www.facebook.com/universidadecatolicaportuguesaoficial/",
        "linkedin": "X"
    },
    {
        "institucion": "Universidade de Lisboa",
        "icono": "universidad",
        "pais": "portugal",
        "region": "lisboa",
        "persona": "Dr. Antonio Manuel da Cruz Serra",
        "cargo": "Reitor da Universidade de Lisboa ",
        "twitter": "x",
        "instagram": "https://www.instagram.com/ulisboa/",
        "facebook": "https://www.facebook.com/UniversidadedeLisboa",
        "linkedin": "https://www.linkedin.com/school/328706/"
    },
    {
        "institucion": "Brown University ",
        "icono": "universidad",
        "pais": "estados unidos",
        "region": "rhode island",
        "persona": "Christina Paxton",
        "cargo": "Rectora de Brown University",
        "twitter": "https://twitter.com/BrownUniversity",
        "instagram": "https://www.instagram.com/brownu/",
        "facebook": "https://www.facebook.com/BrownUniversity",
        "linkedin": "https://www.linkedin.com/school/brown-university/"
    },
    {
        "institucion": "Oxford University",
        "icono": "universidad",
        "pais": "reino unido",
        "region": "oxford",
        "persona": "Dr. Luciano Floridi",
        "cargo": "Professor of Philosophy and Ethics of Information and Director of the Digital Ethics Lab.",
        "twitter": "https://twitter.com/uniofoxford",
        "instagram": "https://www.instagram.com/oxford_uni/",
        "facebook": "https://www.facebook.com/the.university.of.oxford",
        "linkedin": "https://www.linkedin.com/school/4477/"
    },
    {
        "institucion": " Universidad del País Vasco",
        "icono": "universidad",
        "pais": "españa",
        "region": "país vasco",
        "persona": "Nekane Balluerka",
        "cargo": "Rectora de la Universidad del País Vasco",
        "twitter": "https://twitter.com/upvehu",
        "instagram": "X",
        "facebook": "https://www.facebook.com/upvehu/",
        "linkedin": "https://www.linkedin.com/school/15248508/"
    },
    {
        "institucion": "Universidad de Vigo",
        "icono": "universidad",
        "pais": "españa",
        "region": "galicia",
        "persona": "Salustiano Mato de la Iglesia",
        "cargo": "Rector de la Universidad de Vigo ",
        "twitter": "https://twitter.com/uvigo",
        "instagram": "https://www.instagram.com/universidadedevigo/",
        "facebook": "https://www.facebook.com/uvigo",
        "linkedin": "https://www.linkedin.com/school/30664/"
    },
    {
        "institucion": "Universidad del Externado",
        "icono": "universidad",
        "pais": "colombia",
        "region": "bogotá",
        "persona": "Juan Carlos Henao Pérez",
        "cargo": "Rector de la Universidad del Externado",
        "twitter": "https://twitter.com/UExternado",
        "instagram": "https://www.instagram.com/uexternado/",
        "facebook": "https://www.facebook.com/uexternado",
        "linkedin": "https://www.linkedin.com/school/universidad-externado-de-colombia/"
    },
    {
        "institucion": "Colegio de México",
        "icono": "institucion",
        "pais": "méxico",
        "region": "ciudad de méxico",
        "persona": "Silvia Giorguli",
        "cargo": "Presidenta del Colegio de México",
        "twitter": "https://twitter.com/ELCOLMEX",
        "instagram": "https://www.instagram.com/elcolmex/",
        "facebook": "https://www.facebook.com/elcolmex/",
        "linkedin": "https://www.linkedin.com/school/el-colegio-de-mexico/"
    },
    {
        "institucion": "Fundación Donostia International Physics Center",
        "icono": "institucion",
        "pais": "españa",
        "region": "país vasco",
        "persona": "Pedro Miguel Etxenike",
        "cargo": "Presidente de la Fundación Donostia International Physics Center (DIPC) y Catedrático de Física de la Materia Condensada de la Universidad del País Vasco",
        "twitter": "https://twitter.com/DIPCehu",
        "instagram": "X",
        "facebook": "https://www.facebook.com/DIPCehu",
        "linkedin": "X"
    },
    {
        "institucion": "Universidad Nova de Lisboa",
        "icono": "universidad",
        "pais": "portugal",
        "region": "lisboa",
        "persona": "Joao Sàágua",
        "cargo": "Rector de la Universidad Nova de Lisboa ",
        "twitter": "https://twitter.com/NovaUnl",
        "instagram": "X",
        "facebook": "https://www.facebook.com/UniversidadeNOVAdeLisboa/",
        "linkedin": "https://www.linkedin.com/school/universidade-nova-de-lisboa/"
    },
    {
        "institucion": "Universia Portugal",
        "icono": "banco",
        "pais": "portugal",
        "region": "lisboa",
        "persona": "Bernardo Sa Nogueira",
        "cargo": "Director general de Universia Portugal",
        "twitter": "https://twitter.com/UniversiaPT",
        "facebook": "https://www.facebook.com/universia.pt/",
        "linkedin": "https://www.linkedin.com/company/28165130/"
    },
    {
        "institucion": "Universidad de Barcelona ",
        "icono": "universidad",
        "pais": "españa",
        "region": "barcelona",
        "persona": "Dr. Joan Elias i Garcia",
        "cargo": "Rector de la Universidad de Barcelona ",
        "twitter": "https://twitter.com/UniBarcelona",
        "instagram": "https://www.instagram.com/UniBarcelona/",
        "facebook": "https://www.facebook.com/UniversitatdeBarcelona",
        "linkedin": "https://www.linkedin.com/school/university-of-barcelona/"
    },
    {
        "institucion": "Universidad Peruana de Ciencias Aplicadas ",
        "icono": "universidad",
        "pais": "peru",
        "region": "lima",
        "persona": "Dr. Edward Roekaert Embrechts",
        "cargo": "Rector de la Universidad Peruana de Ciencias Aplicadas ",
        "twitter": "https://twitter.com/upcedu",
        "instagram": "https://www.instagram.com/upcedu/",
        "facebook": "https://www.facebook.com/upcedu",
        "linkedin": "https://www.linkedin.com/school/universidad-peruana-de-ciencias-aplicadas/?originalSubdomain=es"
    },
    {
        "institucion": "CETYS Universidad",
        "icono": "universidad",
        "pais": "méxico",
        "region": "ciudad de méxico",
        "persona": "Fernando León García",
        "cargo": "Rector de CETYS Universidad",
        "twitter": "https://twitter.com/cetysuni",
        "instagram": "https://www.instagram.com/cetysens/",
        "facebook": "https://www.facebook.com/CETYS",
        "linkedin": "https://www.linkedin.com/school/111556/"
    },
    {
        "institucion": "Universidad Federal de Río Grande del Sur",
        "icono": "universidad",
        "pais": "brasil",
        "region": "rio grande do sul",
        "persona": "Carlos Alexandre Netto",
        "cargo": "Ex Rector de la UFRGS. Delegado de Brasil para el CRES 2018",
        "twitter": "https://twitter.com/ufrgsnoticias",
        "instagram": "https://www.instagram.com/ufrgsnoticias/?hl=pt",
        "facebook": "https://www.facebook.com/ufrgsnoticias/",
        "linkedin": "https://www.linkedin.com/school/10866/"
    },
    {
        "institucion": "Universidad Autónoma de Madrid",
        "icono": "universidad",
        "pais": "españa",
        "region": "madrid",
        "persona": "Flor Sánchez",
        "cargo": "Universidad Autónoma de Madrid ",
        "twitter": "https://twitter.com/uam_madrid",
        "instagram": "https://www.instagram.com/uammadrid/?hl=es",
        "facebook": "https://www.facebook.com/universidadautonomademadrid",
        "linkedin": "https://www.linkedin.com/school/universidad-autonoma-de-madrid/"
    },
    {
        "institucion": "Universidad de Campinas",
        "icono": "universidad",
        "pais": "brasil",
        "region": "campinas",
        "persona": "Marcelo Knobel",
        "cargo": "Rector de la Universidad de Campinas ",
        "twitter": "https://twitter.com/unicampoficial",
        "instagram": "X",
        "facebook": "https://www.facebook.com/unicampoficial",
        "linkedin": "https://www.linkedin.com/school/universidade-estadual-de-campinas/?originalSubdomain=es"
    },
    {
        "institucion": "Universia Brasil",
        "icono": "banco",
        "pais": "brasil",
        "region": "sao paulo",
        "persona": "Anderson Pereira",
        "cargo": "Director de Universia Brasil ",
        "twitter": "https://twitter.com/universiabrasil",
        "instagram": "https://www.instagram.com/universiabrasil_oficial/",
        "facebook": "https://www.facebook.com/brasil.universia/",
        "linkedin": "https://www.linkedin.com/company/3302408/"
    },
    {
        "institucion": "Universidad de Costa Rica",
        "icono": "universidad",
        "pais": "costa rica",
        "region": "costa rica",
        "persona": "Henning Jensen Pennington",
        "cargo": "Rector de la Universidad de Costa Rica",
        "twitter": "https://twitter.com/UniversidadCR",
        "instagram": "https://www.instagram.com/universidaddecostarica/",
        "facebook": "https://www.facebook.com/UniversidadCostaRica",
        "linkedin": "https://www.linkedin.com/school/universidad-de-costa-rica/"
    },
    {
        "institucion": "Santander Universidades Uruguay",
        "icono": "banco",
        "pais": "uruguay",
        "region": "montevideo",
        "persona": "María Paz Goldaracena",
        "cargo": "Directora de Santander Universidades",
        "twitter": "https://twitter.com/SantanderUni_UY",
        "instagram": "https://www.instagram.com/santanderuni_uy/",
        "facebook": "https://www.facebook.com/SantanderUniversidadesUruguay/",
        "linkedin": "x"
    },
    {
        "institucion": "Universidad Católica del Uruguay",
        "icono": "universidad",
        "pais": "uruguay",
        "region": "montevideo",
        "persona": "P. Dr. Julio Fernández Techera",
        "cargo": "S.I. Rector Universidad Católica del Uruguay",
        "twitter": "https://twitter.com/UCUoficial",
        "instagram": "https://www.instagram.com/ucuoficial/",
        "facebook": "https://www.facebook.com/universidad.catolica.uruguay?ref=hl",
        "linkedin": "https://www.linkedin.com/school/universidad-catolica-del-uruguay/"
    },
    {
        "institucion": "Universidad de Extremadura",
        "icono": "universidad",
        "pais": "españa",
        "region": "extremadura",
        "persona": "Segundo Píriz Durán",
        "cargo": "Rector de la Universidad de Extremadura (España)",
        "twitter": "https://twitter.com/infouex",
        "instagram": "X",
        "facebook": "https://www.facebook.com/universidadextremadura/?ref=share",
        "linkedin": "https://www.linkedin.com/school/university-of-extremadura/"
    },
    {
        "institucion": "Escuela Politécnica del Litoral",
        "icono": "universidad",
        "pais": "ecuador",
        "region": "guayaquil",
        "persona": "Cecilia Paredes",
        "cargo": "Rectora de la Escuela Politécnica del Litoral",
        "twitter": "https://twitter.com/espol",
        "instagram": "https://www.instagram.com/espol1/",
        "facebook": "https://www.facebook.com/espol",
        "linkedin": "https://www.linkedin.com/school/escuela-superior-polit%C3%A9cnica-del-litoral/"
    },
    {
        "institucion": "Conferencia de Consejos Sociales de las Universidades Españolas",
        "icono": "institucion",
        "pais": "españa",
        "region": "gran canaria",
        "persona": "D. Antonio Abril Abadín",
        "cargo": "Presidente de la Conferencia de Consejos Sociales de las Universidades Españolas. Secretario General y del Consejo de Administración de INDITEX",
        "twitter": "https://twitter.com/conferenciacs",
        "instagram": "X",
        "facebook": "X",
        "linkedin": "https://www.linkedin.com/company/conferencia-de-consejos-sociales-de-las-universidades-espa%C3%B1olas/"
    },
    {
        "institucion": "Universidad de St. Andrews",
        "icono": "universidad",
        "pais": "reino unido",
        "region": "escocia",
        "persona": "Sally Mapstone",
        "cargo": "Rectora de la Universidad de St. Andrews",
        "twitter": "https://twitter.com/univofstandrews?lang=es",
        "instagram": "https://www.instagram.com/uniofstandrews/",
        "facebook": "https://www.facebook.com/uniofsta/",
        "linkedin": "https://www.linkedin.com/school/15683/"
    },
    {
        "institucion": "Universidad Nacional de Córdoba",
        "icono": "universidad",
        "pais": "argentina",
        "region": "córdoba",
        "persona": "Hugo Juri",
        "cargo": "Rector de la Universidad Nacional de Córdoba",
        "twitter": "https://twitter.com/unc_cordoba",
        "instagram": "X",
        "facebook": "https://www.facebook.com/universidad.nacional.de.cordoba.oficial/",
        "linkedin": "https://www.linkedin.com/school/universidad-nacional-de-cordoba/"
    },
    {
        "institucion": "Fundación Universia",
        "icono": "banco",
        "pais": "españa",
        "region": "madrid",
        "persona": "Sonia Viñas",
        "cargo": "Directora adjunta de Fundación Universia",
        "twitter": "https://twitter.com/FUniversia",
        "instagram": "https://www.instagram.com/fundacionuniversia/",
        "facebook": "https://www.facebook.com/fundacionuniversia/",
        "linkedin": "https://www.linkedin.com/company/3810744/"
    },
    {
        "institucion": "Universidad de Navarra",
        "icono": "universidad",
        "pais": "españa",
        "region": "navarra",
        "persona": "Alfonso Sánchez-Tabernero",
        "cargo": "Rector de la Universidad de Navarra",
        "twitter": "https://twitter.com/unav",
        "instagram": "https://www.instagram.com/universidaddenavarra/",
        "facebook": "https://www.facebook.com/unav",
        "linkedin": "https://www.linkedin.com/school/26328/"
    },
    {
        "institucion": "Universidad ICESI ",
        "icono": "universidad",
        "pais": "colombia",
        "region": "cali",
        "persona": "Francisco Piedrahita",
        "cargo": "Rector de la Universidad ICESI",
        "twitter": "https://twitter.com/icesi",
        "instagram": "https://www.instagram.com/universidad_icesi/",
        "facebook": "https://www.facebook.com/universidadicesi/",
        "linkedin": "https://www.linkedin.com/school/71423/"
    },
    {
        "institucion": "Universidad del Pacífico ",
        "icono": "universidad",
        "pais": "perú",
        "region": "lima",
        "persona": "Elsa del Castillo Mory",
        "cargo": "Universidad del Pacífico",
        "twitter": "https://twitter.com/udelpacifico?lang=es",
        "instagram": "https://www.instagram.com/udelpacifico/",
        "facebook": "https://www.facebook.com/unipacifico/",
        "linkedin": "https://www.linkedin.com/school/universidad-del-pacifico/"
    },
    {
        "institucion": "Tsinghua University",
        "icono": "universidad",
        "pais": "china",
        "region": "tsinghua",
        "persona": "Bin Yang",
        "cargo": "Vice-President de Tsinghua University. Chairman de Tsinghua University Education Foundation",
        "twitter": "https://twitter.com/Tsinghua_Uni?lang=es",
        "instagram": "https://www.instagram.com/tsinghua_uni/",
        "facebook": "https://www.facebook.com/Tsinghua/?ref=br_rs",
        "linkedin": "https://www.linkedin.com/school/14022/"
    },
    {
        "institucion": "Instituto Nacional de DDHH",
        "icono": "institucion",
        "pais": "chile",
        "region": "santiago de chile",
        "persona": "María Soledad Cisternas Réyes",
        "cargo": "Miembro del Consejo Consultivo del Instituto Nacional de DDHH",
        "twitter": "https://twitter.com/inddhh?lang=es",
        "instagram": "X",
        "facebook": "https://www.facebook.com/indhchile",
        "linkedin": "X"
    },
    {
        "institucion": "Universidad de Santiago de Compostela",
        "icono": "universidad",
        "pais": "españa",
        "region": "santiago de compostela",
        "persona": "María del Mar Lorenzo",
        "cargo": "Docente de la Universidad de Santiago de Compostela",
        "twitter": "https://twitter.com/universidadeusc",
        "instagram": "x",
        "facebook": "https://www.facebook.com/UniversidadeUSC/",
        "linkedin": "https://www.linkedin.com/school/universidad-de-santiago-de-compostela/"
    },
    {
        "institucion": "Universidad de Valencia ",
        "icono": "universidad",
        "pais": "españa",
        "region": "valencia",
        "persona": "Mª Antonia García Benau",
        "cargo": "Catedrática de la Universidad de Valencia",
        "twitter": "https://twitter.com/uv_eg?lang=es",
        "instagram": "https://www.instagram.com/universitatvalencia/",
        "facebook": "https://www.facebook.com/universitatdevalencia/",
        "linkedin": "https://www.linkedin.com/school/university-of-valencia/"
    },
    {
        "institucion": " Universidad Antonio Nariño",
        "icono": "universidad",
        "pais": "colombia",
        "region": "bogotá",
        "persona": "Martha Losada Falk",
        "cargo": "Rectora de la Universidad Antonio Nariño",
        "twitter": "https://twitter.com/UANTONIONARINO",
        "instagram": "x",
        "facebook": "https://www.facebook.com/Universidad-Antonio-Nari%C3%B1o-Perfil-Oficial-292977960813556/",
        "linkedin": "https://www.linkedin.com/school/universidad-antonio-nari-o/"
    },
    {
        "institucion": "Universitat Politècnica de Catalunya ",
        "icono": "universidad",
        "pais": "españa",
        "region": "cataluña",
        "persona": "Francesc Torres",
        "cargo": "Rector de la Universitat Politècnica de Catalunya",
        "twitter": "https://twitter.com/la_UPC",
        "instagram": "https://www.instagram.com/la_upc/",
        "facebook": "https://www.facebook.com/universitatUPC",
        "linkedin": "https://www.linkedin.com/school/universitat-politecnica-de-catalunya/"
    },
    {
        "institucion": "Santander Universidades España",
        "icono": "banco",
        "pais": "españa",
        "region": "madrid",
        "persona": "Javier López",
        "cargo": "Director de Impacto Social ",
        "twitter": "https://twitter.com/universia",
        "instagram": "https://www.instagram.com/universia_net",
        "facebook": "https://www.facebook.com/universianet/",
        "linkedin": "https://www.linkedin.com/company/28162346/"
    },
    {
        "institucion": "Universidad Autónoma de Madrid ",
        "icono": "universidad",
        "pais": "españa",
        "region": "madrid",
        "persona": "Rafael Garesse",
        "cargo": "Rector de la Universidad Autónoma de Madrid",
        "twitter": "https://twitter.com/uam_madrid",
        "instagram": "https://www.instagram.com/uammadrid/?hl=es",
        "facebook": "https://www.facebook.com/universidadautonomademadrid",
        "linkedin": "https://www.linkedin.com/school/universidad-autonoma-de-madrid/"
    },
    {
        "institucion": "Universidad de Sao Paulo",
        "icono": "universidad",
        "pais": "brasil",
        "region": "sao paulo",
        "persona": "Vahan Agopyan",
        "cargo": "Rector de la Universidad de Sao Paulo",
        "twitter": "https://twitter.com/usponline",
        "instagram": "X",
        "facebook": "https://www.facebook.com/usponline/",
        "linkedin": "https://www.linkedin.com/school/universidade-de-s-o-paulo/"
    },
    {
        "institucion": "Babson College",
        "icono": "universidad",
        "pais": "estados unidos",
        "region": "massachusetts",
        "persona": "Kerry Healey",
        "cargo": "Presidenta del Babson College",
        "twitter": "https://twitter.com/babson?lang=es",
        "instagram": "https://www.instagram.com/babsoncollege/?hl=es",
        "facebook": "https://www.facebook.com/babsoncollege/",
        "linkedin": "https://www.linkedin.com/school/babson-college/"
    },
    {
        "institucion": "Universidad Católica de Chile",
        "icono": "universidad",
        "pais": "chile",
        "region": "santiago de chile",
        "persona": "Conrad von Igel",
        "cargo": "Director del Centro de Innovación UC Anacleto Angelini",
        "twitter": "https://twitter.com/ucatolica",
        "instagram": "https://www.instagram.com/ucatolicaoficial/",
        "facebook": "https://www.facebook.com/ucatolica",
        "linkedin": "https://www.linkedin.com/school/399270/"
    },
    {
        "institucion": "TrepCamp ",
        "icono": "institucion",
        "pais": "estados unidos",
        "region": "california",
        "persona": "Fernando Sepúlveda",
        "cargo": "Fundador y CEO de TrepCamp",
        "twitter": "https://twitter.com/TrepCampUSA",
        "instagram": "https://www.instagram.com/trepcamp/",
        "facebook": "https://www.facebook.com/profile.php?id=100014236846614",
        "linkedin": "https://www.linkedin.com/company/24789384/"
    },
    {
        "institucion": "Anima Educaçao",
        "icono": "institucion",
        "pais": "brasil",
        "region": "sao paulo",
        "persona": "Sr. Daniel Castanho",
        "cargo": "Presidente de Anima Educaçao",
        "twitter": "https://twitter.com/animaedu",
        "instagram": "https://www.instagram.com/animainstituto/",
        "facebook": "https://www.facebook.com/AnimaEducacao/?ref=br_rs",
        "linkedin": "https://www.linkedin.com/company/892822/"
    },
    {
        "institucion": "Universia Corporativo",
        "icono": "banco",
        "pais": "españa",
        "region": "madrid",
        "persona": "Beatriz Sevillano",
        "cargo": "Directora de empleo de Universia corporativo",
        "twitter": "https://twitter.com/universia",
        "instagram": "https://www.instagram.com/universia_net",
        "facebook": "https://www.facebook.com/universianet/",
        "linkedin": "https://www.linkedin.com/company/28162346/"
    },
    {
        "institucion": "Universitat Pompeu Fabra",
        "icono": "universidad",
        "pais": "españa",
        "region": "barcelona",
        "persona": "Jaume Casals",
        "cargo": "Rector de la Universitat Pompeu Fabra",
        "twitter": "https://twitter.com/upfbarcelona",
        "instagram": "https://www.instagram.com/upfbarcelona/",
        "facebook": "https://www.facebook.com/UPFBarcelona/",
        "linkedin": "https://www.linkedin.com/school/universitat-pompeu-fabra/"
    },
    {
        "institucion": "Universidad Carlos III",
        "icono": "universidad",
        "pais": "españa",
        "region": "madrid",
        "persona": "Juan Romo",
        "cargo": "Rector de la Universidad Carlos III",
        "twitter": "https://twitter.com/uc3m",
        "instagram": "https://www.instagram.com/universidadcarlosiiidemadrid/",
        "facebook": "https://www.facebook.com/uc3m",
        "linkedin": "https://www.linkedin.com/school/universidad-carlos-iii-de-madrid/"
    },
    {
        "institucion": "Draper University",
        "icono": "universidad",
        "pais": "estados unidos",
        "region": "california",
        "persona": "Tim Draper",
        "cargo": "Fundador de la Draper University",
        "twitter": "https://twitter.com/draper_u",
        "instagram": "https://www.instagram.com/draperuniversity/",
        "facebook": "https://www.facebook.com/DraperUniversity/",
        "linkedin": "https://www.linkedin.com/school/2746862/"
    },
    {
        "institucion": "Fundación Pachacutec",
        "icono": "institucion",
        "pais": "perú",
        "region": "lima",
        "persona": "Gastón Acúrio",
        "cargo": "Instituto de cocina Pachacutec ",
        "twitter": "https://twitter.com/fpachacutec",
        "instagram": "https://www.instagram.com/fundacionpachacutec/",
        "facebook": "https://www.facebook.com/fundacionpachacutec/",
        "linkedin": "https://www.linkedin.com/school/22481154/"
    },
    {
        "institucion": "Panelli Motta Cabrera ",
        "icono": "institucion",
        "pais": "brasil",
        "region": "sao paulo",
        "persona": "Luiz Carlos de Queiróz Cabrera",
        "cargo": "Sócio da Panelli Motta Cabrera ",
        "twitter": "X",
        "instagram": "X",
        "facebook": "X",
        "linkedin": "https://www.linkedin.com/company/amrop-panelli-motta-cabrera/?originalSubdomain=es"
    },
    {
        "institucion": "Universidad St. Mary's Twickenham",
        "icono": "universidad",
        "pais": "reino unido",
        "region": "londres",
        "persona": "Francisc Campbell",
        "cargo": "Rector de la Universidad St. Mary's Twickenham",
        "twitter": "https://twitter.com/YourStMarys",
        "instagram": "https://www.instagram.com/yourstmarys/",
        "facebook": "https://www.facebook.com/yourstmarys/",
        "linkedin": "https://www.linkedin.com/school/19469/"
    },
    {
        "institucion": "Itaú Unibanco",
        "icono": "institucion",
        "pais": "brasil",
        "region": "sao paulo",
        "persona": "Denise Hills",
        "cargo": "Itaú Unibanco. Presidenta da Rede Brasil do Pacto Global (ONU) ",
        "twitter": "https://twitter.com/itauunibanco_ri",
        "instagram": "https://www.instagram.com/itau/?hl=es",
        "facebook": "https://www.facebook.com/itau/?rc=p",
        "linkedin": "https://www.linkedin.com/company/itau?originalSubdomain=es"
    },
    {
        "institucion": "HEM Business School",
        "icono": "universidad",
        "pais": "marruecos",
        "region": "rabat",
        "persona": "Yasmine Benamour",
        "cargo": "Managing Director",
        "twitter": "https://twitter.com/HEMofficiel",
        "instagram": "x",
        "facebook": "https://www.facebook.com/Groupe.HEM.Officiel",
        "linkedin": "https://www.linkedin.com/school/15248559/"
    },
    {
        "institucion": "Universidad de la Matanza",
        "icono": "universidad",
        "pais": "argentina",
        "region": "san justo",
        "persona": "Daniel Martínez",
        "cargo": "Rector de la Universidad de la Matanza",
        "twitter": "https://twitter.com/UnlamOficial",
        "instagram": "https://www.instagram.com/unlamoficial/",
        "facebook": "https://www.facebook.com/UnlamOficial",
        "linkedin": "https://www.linkedin.com/school/universidad-nacional-de-la-matanza/?originalSubdomain=es"
    },
    {
        "institucion": "Santander Universidades Argentina",
        "icono": "banco",
        "pais": "argentina",
        "region": "buenos aires",
        "persona": "Marcelo Fernández",
        "cargo": "Director de Santander Universidades Argentina",
        "twitter": "X",
        "instagram": "X",
        "facebook": "X",
        "linkedin": "X"
    },
    {
        "institucion": "Universidad de Salamanca",
        "icono": "universidad",
        "pais": "españa",
        "region": "salamanca",
        "persona": "Ricardo Rivero",
        "cargo": "Rector de la Universidad de Salamanca",
        "twitter": "https://twitter.com/usal",
        "instagram": "https://www.instagram.com/usal/",
        "facebook": "https://www.facebook.com/universidaddesalamanca/",
        "linkedin": "https://www.linkedin.com/school/57126/"
    },
    {
        "institucion": "Universidad Cooperativa de Colombia",
        "icono": "universidad",
        "pais": "colombia",
        "region": "bogotá",
        "persona": "Dra. Maritza Rondon",
        "cargo": "Rectora de la Universidad Cooperativa de Colombia",
        "twitter": "https://twitter.com/UCooperativaCol",
        "instagram": "X",
        "facebook": "https://www.facebook.com/UCooperativadeColombia/",
        "linkedin": "https://www.linkedin.com/school/universidad-cooperativa-de-colombia/"
    },
    {
        "institucion": "London School of Economics",
        "icono": "universidad",
        "pais": "reino unido",
        "region": "londres",
        "persona": "Andrés Rodriguez-Pose",
        "cargo": "Profesor de Geografía Económica. Editor de Economic Geografy",
        "twitter": "https://twitter.com/LSEnews",
        "instagram": "https://www.instagram.com/londonschoolofeconomics/",
        "facebook": "https://www.facebook.com/lseps/",
        "linkedin": "https://www.linkedin.com/school/6544/"
    },
    {
        "institucion": "Universidad de Granada",
        "icono": "universidad",
        "pais": "españa",
        "region": "granada",
        "persona": "Pilar Aranda Ramírez",
        "cargo": "Rectora de la Universidad de Granada",
        "twitter": "https://twitter.com/canalugr",
        "instagram": "https://www.instagram.com/canalugr/",
        "facebook": "https://www.facebook.com/universidadgranada/",
        "linkedin": "https://www.linkedin.com/school/28491/"
    },
    {
        "institucion": "Universidad Nacional Mayor de San Marcos de Lima",
        "icono": "universidad",
        "pais": "perú",
        "region": "lima",
        "persona": "Dr. Orestes Cachay Boza",
        "cargo": "Universidad Nacional Mayor de San Marcos de Lima",
        "twitter": "https://twitter.com/UNMSM_",
        "instagram": "x",
        "facebook": "https://www.facebook.com/1551UNMSM",
        "linkedin": "https://www.linkedin.com/school/490454/"
    },
    {
        "institucion": "Universidad Autónoma de Madrid",
        "icono": "universidad",
        "pais": "españa",
        "region": "madrid",
        "persona": "Prof. Antonio Vazquez Barquero",
        "cargo": "Catedrático de Economía y Profesor Emérito de la Universidad Autónoma de Madrid",
        "twitter": "https://twitter.com/UAM_Madrid",
        "instagram": "https://www.instagram.com/uammadrid/",
        "facebook": "https://www.facebook.com/universidadautonomademadrid/",
        "linkedin": "https://www.linkedin.com/in/universidadautonomademadrid/"
    },
    {
        "institucion": "Universidad Nacional de Lomas de Zamora ",
        "icono": "universidad",
        "pais": "argentina",
        "region": "lomas",
        "persona": "Dr. Diego Molea",
        "cargo": "Rector de la Universidad Nacional de Lomas de Zamora",
        "twitter": "https://twitter.com/UNLZoficial",
        "instagram": "https://www.instagram.com/unlzoficial/",
        "facebook": "https://www.facebook.com/UNLZoficial/",
        "linkedin": "https://www.linkedin.com/company/2127867/"
    },
    {
        "institucion": "Gobierno de España",
        "icono": "institucion",
        "pais": "españa",
        "region": "madrid",
        "persona": "Mariano Rajoy",
        "cargo": "Presidente del Gobierno de España",
        "twitter": "https://twitter.com/desdelamoncloa",
        "instagram": "x",
        "facebook": "x",
        "linkedin": "x"
    },
    {
        "institucion": "SEGIB",
        "icono": "institucion",
        "pais": "españa",
        "region": "madrid",
        "persona": "Rebeca Grynspan",
        "cargo": "Secretaría General Iberoamericana",
        "twitter": "https://twitter.com/SEGIBdigital",
        "instagram": "https://www.instagram.com/segibdigital/",
        "facebook": "https://www.facebook.com/SEGIB/",
        "linkedin": "https://www.linkedin.com/company/240358/"
    },
    {
        "institucion": "Universitat Politècnica de València",
        "icono": "universidad",
        "pais": "españa",
        "region": "valencia",
        "persona": "Rector Francisco Mora",
        "cargo": "Presidente del Comité Académico",
        "twitter": "https://twitter.com/UPV?lang=es",
        "instagram": "https://www.instagram.com/instaupv/",
        "facebook": "https://www.facebook.com/UPV/",
        "linkedin": "https://www.linkedin.com/school/166618/"
    },
    {
        "institucion": "Santander Universidades ",
        "icono": "banco",
        "pais": "españa",
        "region": "madrid",
        "persona": "Matías Rodriguez Inciarte",
        "cargo": "Presidente Santander Universidades ",
        "twitter": "https://twitter.com/bancosantander?lang=es",
        "facebook": "https://www.facebook.com/bancosantander/",
        "linkedin": "https://www.linkedin.com/company/banco-santander/?originalSubdomain=es"
    },
    {
        "institucion": "Universidad de Buenos Aires",
        "icono": "universidad",
        "pais": "argentina",
        "region": "buenos aires",
        "persona": "Rector Alberto Egdardo Barbieri ",
        "cargo": "Presidente Comité Internacional ",
        "twitter": "https://twitter.com/UBAonline",
        "instagram": "https://www.instagram.com/ubaoficial/",
        "facebook": "https://www.facebook.com/ubaonline/",
        "linkedin": "https://www.linkedin.com/school/338240/"
    },
    {
        "institucion": "Universidad de Salamanca",
        "icono": "universidad",
        "pais": "españa",
        "region": "salamanca",
        "persona": "Ricardo Rivero",
        "cargo": "Rector de la Universidad de Salamanca",
        "twitter": "https://twitter.com/usal",
        "instagram": "https://www.instagram.com/usal/",
        "facebook": "https://www.facebook.com/universidaddesalamanca/",
        "linkedin": "https://www.linkedin.com/school/57126/"
    },
    {
        "institucion": "Universidad de Alicante",
        "icono": "universidad",
        "pais": "españa",
        "region": "alicante",
        "persona": "Francis Mojica",
        "cargo": "Microbiólogo, investigador y profesor titular del Departamento de Fisiología, Genética y Microbiología de la Universidad de Alicante ",
        "twitter": "https://twitter.com/ua_universidad?lang=es",
        "instagram": "https://www.instagram.com/ua_universidad/?hl=es",
        "facebook": "https://www.facebook.com/campusUA/",
        "linkedin": "https://www.linkedin.com/company/university-of-alicante/?originalSubdomain=es"
    },
    {
        initial_title: "EMPIEZA A NAVEGAR",
        initial_text: "Por el universo de redes sociales del IV Encuentro de Rectores",
    },
]